drop table if exists books CASCADE;
drop table if exists authors;
drop table if exists genres;
drop table if exists users;
drop table if exists comments;

create table authors (
    id bigint generated by default as identity,
    name varchar(255) not null,
    country varchar(255) not null,
    primary key (id),
    constraint unique_author unique (name, country)
);

create table genres (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    primary key (id)
);

create table books (
    id bigint generated by default as identity,
    title varchar(255) not null,
    page_count integer,
    author_id bigint,
    genre_id bigint,
    primary key (id),
    constraint unique_book unique (title, author_id)
);

create table users (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    password varchar(255),
    role varchar(255),
    primary key (id)
);

create table comments (
    id bigint generated by default as identity,
    text text,
    book_id bigint,
    primary key (id)
);

alter table books add constraint FK_TO_AUTHORS foreign key (author_id) references authors;
alter table books add constraint FK_TO_GENRES foreign key (genre_id) references genres;
alter table comments add constraint FK_TO_BOOKS foreign key (book_id) references books on delete cascade;