version: '3'
services:
  exploit-source:
    build:
      context: ./exploit-source/
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/source?reWriteBatchedInserts=true
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=postgres:5432
    networks:
      - nw
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=source
    networks:
      - nw
networks:
  nw:
