version: '3'
services:
  exploit-source:
    build:
      context: ./exploit-source/
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/source?reWriteBatchedInserts=true
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=postgres:5432
    networks:
      - nw
  report-analyzer:
    build:
      context: ./report-analyzer/
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8081:8081"
    depends_on:
      - exploit-source
    environment:
      - EXPLOIT_SOURCE_URL=http://exploit-source:8082
      - WAIT_FOR=exploit-source:8082
    networks:
      - nw
  web-ui:
    build:
      context: ./web-ui/
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "3000:3000"
    depends_on:
      - report-analyzer
    networks:
      - nw
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=source
    networks:
      - nw
networks:
  nw:
