spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 30
      hibernate.order_inserts: true
      hibernate.order_updates: true

logging:
  level:
    org.springframework: INFO
    ru.dvkombarov: DEBUG