spring:
  batch:
    job:
      enabled: false

  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    platform: prod

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    mongodb:
      database: migration
      host: localhost
      port: 27017
      auto-index-creation: true

app:
  chunksize: 10